# Site settings
title: Service-Injector
email: phantom@ydn.ru
description: JS library for bringing your SaaS on clients' sites
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock']
highlighter: rouge
permalink: pretty
url: "http://orienteerdw.github.io/"
baseurl: "/service-injector"

# Build settings
markdown: kramdown
